// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVV3LV2lgXpLC5x6ct7FMtjSrNJs9UFc',
    appId: '1:346711918519:web:a1511cc0a161e9483c8a32',
    messagingSenderId: '346711918519',
    projectId: 'quick-cng',
    authDomain: 'quick-cng.firebaseapp.com',
    storageBucket: 'quick-cng.firebasestorage.app',
    measurementId: 'G-JKP03MW2Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWl5CsMoilBdO5Gcvj7EANBfV1dRQoi9k',
    appId: '1:346711918519:android:803e848ce7d3b93a3c8a32',
    messagingSenderId: '346711918519',
    projectId: 'quick-cng',
    storageBucket: 'quick-cng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTUlT-tlzE3NgFInrC_iC9MS9mNb08IwU',
    appId: '1:346711918519:ios:537ac947d4bba9633c8a32',
    messagingSenderId: '346711918519',
    projectId: 'quick-cng',
    storageBucket: 'quick-cng.firebasestorage.app',
    iosBundleId: 'com.yash.quickcng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTUlT-tlzE3NgFInrC_iC9MS9mNb08IwU',
    appId: '1:346711918519:ios:8a19c18807404bf13c8a32',
    messagingSenderId: '346711918519',
    projectId: 'quick-cng',
    storageBucket: 'quick-cng.firebasestorage.app',
    iosBundleId: 'com.example.quickcng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpVV3LV2lgXpLC5x6ct7FMtjSrNJs9UFc',
    appId: '1:346711918519:web:a4870f3967ac2d7c3c8a32',
    messagingSenderId: '346711918519',
    projectId: 'quick-cng',
    authDomain: 'quick-cng.firebaseapp.com',
    storageBucket: 'quick-cng.firebasestorage.app',
    measurementId: 'G-RQ04M76LQ7',
  );

}