name: Flutter Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.8'

      - name: Install dependencies
        run: flutter pub get

      # 3.5️⃣ Create Firebase Options file from Secret
      - name: Create firebase_options.dart
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 --decode > lib/firebase_options.dart

      - name: Analyze code
        run: flutter analyze

      - name: Increment version code
        id: version
        run: |
          current_code=$(grep "version:" pubspec.yaml | sed 's/.*+//')
          new_code=$((current_code + 1))
          echo "new_version_code=$new_code" >> $GITHUB_OUTPUT
          sed -i "s/+${current_code}/+${new_code}/" pubspec.yaml

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-v${{ steps.version.outputs.new_version_code }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk-v${{ steps.version.outputs.new_version_code }}
          path: build/app/outputs/flutter-apk/app-release-v${{ steps.version.outputs.new_version_code }}.apk

      - name: Deploy to Play Store Internal Test
        if: github.ref == 'refs/heads/main'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.PLAY_STORE_JSON }}
          packageName: com.yash.quickcng
          releaseFiles: build/app/outputs/flutter-apk/app-release-v${{ steps.version.outputs.new_version_code }}.apk
          track: internal
